[project]
name = "pentestagent-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno==1.6.4",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.13",
    "aiosignal==1.3.2",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "apscheduler==3.11.0",
    "attrs==25.3.0",
    "backoff==2.2.1",
    "beautifulsoup4==4.13.4",
    "boto3==1.34.34",
    "botocore==1.34.162",
    "certifi==2025.6.15",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "cryptography==43.0.3",
    "distro==1.9.0",
    "dnspython==2.7.0",
    "docstring-parser==0.16",
    "email-validator==2.2.0",
    "fastapi==0.115.13",
    "fastapi-sso==0.16.0",
    "filelock==3.18.0",
    "frozenlist==1.7.0",
    "fsspec==2025.5.1",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "googlesearch-python==1.3.0",
    "greenlet==3.2.3",
    "gunicorn==23.0.0",
    "h11==0.16.0",
    "hf-xet==1.1.5",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "httpx-sse==0.4.1",
    "huggingface-hub==0.33.1",
    "idna==3.10",
    "importlib-metadata==8.7.0",
    "jinja2==3.1.6",
    "jiter==0.10.0",
    "jmespath==1.0.1",
    "jsonschema==4.24.0",
    "jsonschema-specifications==2025.4.1",
    "litellm==1.73.1",
    "litellm-enterprise==0.1.9",
    "litellm-proxy-extras==0.2.5",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mcp==1.9.3",
    "mdurl==0.1.2",
    "multidict==6.5.1",
    "oauthlib==3.3.1",
    "openai==1.91.0",
    "orjson==3.10.18",
    "outcome==1.3.0.post0",
    "packaging==25.0",
    "propcache==0.3.2",
    "pycountry==24.6.1",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pydantic-settings==2.10.1",
    "pygments==2.19.2",
    "pyjwt==2.10.1",
    "pynacl==1.5.0",
    "pysocks==1.7.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "python-multipart==0.0.18",
    "pyyaml==6.0.2",
    "redis==6.2.0",
    "referencing==0.36.2",
    "regex==2024.11.6",
    "requests==2.32.4",
    "rich==13.7.1",
    "rpds-py==0.25.1",
    "rq==2.4.0",
    "s3transfer==0.10.4",
    "selenium==4.34.0",
    "shellingham==1.5.4",
    "six==1.17.0",
    "smmap==5.0.2",
    "sniffio==1.3.1",
    "sortedcontainers==2.4.0",
    "soupsieve==2.7",
    "sqlalchemy==2.0.41",
    "sse-starlette==2.3.6",
    "starlette==0.46.2",
    "tenacity>=9.1.2",
    "tiktoken==0.9.0",
    "tokenizers==0.21.2",
    "tomli==2.2.1",
    "tqdm==4.67.1",
    "trio==0.30.0",
    "trio-websocket==0.12.2",
    "typer==0.16.0",
    "typing-extensions==4.14.0",
    "typing-inspection==0.4.1",
    "tzlocal==5.3.1",
    "urllib3==2.4.0",
    "uvicorn==0.29.0",
    "uvloop==0.21.0",
    "webdriver-manager==4.0.2",
    "websocket-client==1.8.0",
    "websockets==13.1",
    "wsproto==1.2.0",
    "yarl==1.20.1",
    "zipp==3.23.0",
]
